# バージョン指定
version: '3'

# 各コンテナ定義
services:
  # ---------------------------------
  # アプリケーション(Laravel)
  # ---------------------------------
  app:
    # コンテナ名
    container_name: simple_board_application_container
    # Dockerfileからコンテナをビルドする
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    # 作業ディレクトリの指定
    working_dir: /var/www/html
    # データベースの後に起動
    depends_on:
      - mysql
    # ディレクトリの同期
    volumes:
      # 公開用ディレクトリ（laravelプロジェクトが入る）
      - ./docker/app/src:/var/www/html
      # phpの設定ファイル
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    environment:
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}

  # ---------------------------------
  # Webサーバー(Nginx)
  # ---------------------------------
  web:
    container_name: simple_board_nginx_container
    image: nginx:1.21
    # ポート解放（ホスト:コンテナ）
    ports:
      - '8080:${WEB_PORT}'
    working_dir: /var/www/html
    depends_on:
      - app
    volumes:
      - ./docker/nginx/src:/var/www/html
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: 'Asia/Tokyo'

  # ---------------------------------
  # データベース(MySQL)
  # ---------------------------------
  mysql:
    container_name: simple_board_mysql_container
    image: mysql:5.7
    expose:
      - '${DB_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql                    # データ
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf        # 設定ファイル
      - ./docker/mysql/init_sql:/docker-entrypoint-initdb.d   # 初期化SQL
    # 初期コマンド実行
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # ---------------------------------
  # クライアントツール(PhpMyAdmin)
  # ---------------------------------
  phpmyadmin:
    container_name: simple_board_phpmyadmin_container
    image: phpmyadmin:5.1
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: simple_board_mysql_container
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    ports:
    - '4040:${WEB_PORT}'
