# バージョン指定
version: '3'

# 各コンテナ定義
services:
  # ---------------------------------
  # アプリケーションサーバー（React.js）
  # ---------------------------------
  app:
    # コンテナ名
    container_name: simple_board_app
    # Dockerfileからビルド
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    # ポート
    ports:
      - '${DEV_PORT}:${DEV_PORT}'
    # ボリューム（Bind Mounts）
    volumes:
      - ./docker/app/src:/app
    # 作業ディレクトリ
    working_dir: /app
    # 環境変数
    environment:
      - PORT=${DEV_PORT}                # 開発用ポート
      - TZ=${TZ}
    # 指定コンテナの後に起動
    depends_on:
      - db
      - api
    tty: true

  # ---------------------------------
  # APIサーバー（Laravel）
  # ---------------------------------
  api:
    # コンテナ名
    container_name: simple_board_api
    # Dockerfileからビルド
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    # ポート指定
    ports:
      - '${API_PORT}:${API_PORT}'
    # ボリューム（Bind Mounts）
    volumes:
      - ./docker/api/src:/var/www/html                          # 公開用ディレクトリ（laravelプロジェクト格納先）
      - ./docker/api/php.ini:/usr/local/etc/php/php.ini   
    # 作業ディレクトリ
    working_dir: /var/www/html
    # 環境変数
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    # 指定コンテナの後に起動
    depends_on:
      - db

  # ---------------------------------
  # Webサーバー(Nginx)
  # ---------------------------------
  web:
    # コンテナ名
    container_name: simple_board_web
    # 公式イメージからビルド
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    # ポート指定（ホスト:コンテナ）
    ports:
      - '${APP_PORT}:${WEB_PORT}'
    # ボリューム（Bind Mounts）
    volumes:
      - ./docker/web/logs:/var/log/nginx     # ログフォルダー
    # 環境変数
    environment:
      - TZ=${TZ}
    # 指定コンテナ起動完了後に起動
    depends_on:
      - app
      - db

  # ---------------------------------
  # データベース(MySQL)
  # ---------------------------------
  db:
    # コンテナ名
    container_name: simple_board_db
    # 公式イメージからビルド
    image: mysql:8
    # ポート指定（コンテナ）
    expose:
      - '${DB_PORT}'
    # ボリューム（Bind Mounts）
    volumes:
      - ./docker/db/data:/var/lib/mysql                    # データ
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf        # 設定ファイル
      - ./docker/db/logs:/var/log/mysql                    # ログファイル
      - ./docker/db/sql:/docker-entrypoint-initdb.d        # 初期化SQL
    # 環境変数
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - TZ=${TZ}

  # ---------------------------------
  # クライアントツール(PhpMyAdmin)
  # ---------------------------------
  client:
    # コンテナ名
    container_name: simple_board_client
    # 公式イメージからビルド
    image: phpmyadmin:5
    # ポート指定（ホスト:コンテナ）
    ports:
      - '${CLIENT_PORT}:${WEB_PORT}'
    # ボリューム（Bind Mounts）
    volumes:
      - ./docker/client/sessions:/sessions
    # 環境変数
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=${DB_HOST}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    # 指定コンテナ起動完了後に起動
    depends_on:
      - db
