# バージョン指定
version: '3'

# 各コンテナ定義
services:
  # ---------------------------------
  # アプリケーション（Django）
  # ---------------------------------
  app:
    # コンテナ名
    container_name: simple_board_app
    # Dockerfileからビルド
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    # ポート指定
    ports:
      - 8000:8000
    # ボリューム（Bind Mounts）
    volumes:
      - ./docker/app/src:/app
    # 環境変数
    env_file:
      - ./.env.dev
    # 作業ディレクトリ
    working_dir: /app
    # 起動し続ける
    tty: true
    # 指定コンテナの後に起動
    depends_on:
      - db

  # ---------------------------------
  # Webサーバー(Nginx)
  # ---------------------------------
  # web:
  #   # コンテナ名
  #   container_name: simple_board_web
  #   # 公式イメージからビルド
  #   image: nginx:1.23
  #   # ポート指定（ホスト:コンテナ）
  #   ports:
  #     - '8080:${WEB_PORT}'
  #   # ボリューム（Bind Mounts）
  #   volumes:
  #     # - ./docker/app/src:/var/www/html            # nginx側にもappのソースを置く（なぜかcssやjsなどが参照できないため）
  #     - ./docker/web/logs:/var/log/nginx
  #     - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
  #   # 環境変数
  #   environment:
  #     - TZ=${TZ}
  #   # 作業ディレクトリ
  #   working_dir: /var/www/html
  #   # 指定コンテナ起動完了後に起動
  #   depends_on:
  #     - app

  # ---------------------------------
  # データベース(PostgreSQL)
  # ---------------------------------
  db:
    # コンテナ名
    container_name: simple_board_db
    # 公式イメージからビルド
    image: postgres:14
    # ポート指定（コンテナ）
    ports:
      - '5432:5432'
    # ボリューム（Bind Mounts）
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data                       # データ
      - ./docker/db/sql:/docker-entrypoint-initdb.d                     # 初期化SQL
      - ./docker/db/postgresql.conf:/etc/postgresql/postgresql.conf     # 設定ファイル
    # 環境変数 
    env_file:
      - ./.env.dev

  # ---------------------------------
  # クライアントツール(pgAdmin)
  # ---------------------------------
  client:
    # コンテナ名
    container_name: simple_board_client
    # 公式イメージからビルド
    image: dpage/pgadmin4
    # ポート指定（ホスト:コンテナ）
    ports:
      - '4040:80'
    # ボリューム（Bind Mounts）
    volumes:
      - ./docker/client/pgadmin:/var/lib/pgadmin
    # 環境変数
    env_file:
      - ./.env.dev
    # 指定コンテナ起動完了後に起動
    depends_on:
      - db
