# Generated by Django 3.2 on 2022-08-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20220810_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='fan_user_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
